# This workflow will run 'go test' on the project when creating a PR (or trying to push to) main
name: Go Test CI

on:
  push:
    branches: [ main, develop ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'
        cache: true

    - name: Get CPU count
      id: cpu
      run: echo "count=$(nproc 2>/dev/null || sysctl -n hw.ncpu || echo 2)" >> $GITHUB_OUTPUT

    - name: Run tests
      env:
        GETH_RPC_URL: ${{ secrets.GETH_RPC_URL }}
        GETH_WS_URL: ${{ secrets.GETH_WS_URL }}
        GETH_API_KEY: ${{ secrets.GETH_API_KEY }}
        DEFRADB_URL: http://localhost:9181
        LOG_LEVEL: error
      run: |
        go test -parallel=${{ steps.cpu.outputs.count  }} ./...

    - name: Upload coverage
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.out
        flags: unittests
        name: codecov-umbrella
      continue-on-error: true
